package server

type ArenaStatistics struct {
	Level                        uint64  `json:"Level"`
	Stuns                        uint64  `json:"Stuns,omitempty"`
	TopSpeedsTotal               float64 `json:"TopSpeedsTotal,omitempty"`
	HighestArenaWinStreak        uint64  `json:"HighestArenaWinStreak,omitempty"`
	ArenaWinPercentage           float64 `json:"ArenaWinPercentage,omitempty"`
	ArenaWins                    uint64  `json:"ArenaWins,omitempty"`
	ShotsOnGoalAgainst           uint64  `json:"ShotsOnGoalAgainst,omitempty"`
	Clears                       uint64  `json:"Clears,omitempty"`
	AssistsPerGame               float64 `json:"AssistsPerGame,omitempty"`
	Passes                       uint64  `json:"Passes,omitempty"`
	AveragePossessionTimePerGame float64 `json:"AveragePossessionTimePerGame,omitempty"`
	Catches                      uint64  `json:"Catches,omitempty"`
	PossessionTime               float64 `json:"PossessionTime,omitempty"`
	StunsPerGame                 float64 `json:"StunsPerGame,omitempty"`
	ShotsOnGoal                  uint64  `json:"ShotsOnGoal,omitempty"`
	PunchesReceived              uint64  `json:"PunchesReceived,omitempty"`
	CurrentArenaWinStreak        uint64  `json:"CurrentArenaWinStreak,omitempty"`
	Assists                      uint64  `json:"Assists,omitempty"`
	Interceptions                uint64  `json:"Interceptions,omitempty"`
	HighestStuns                 uint64  `json:"HighestStuns,omitempty"`
	AverageTopSpeedPerGame       float64 `json:"AverageTopSpeedPerGame,omitempty"`
	XP                           uint64  `json:"XP,omitempty"`
	ArenaLosses                  uint64  `json:"ArenaLosses,omitempty"`
	SavesPerGame                 float64 `json:"SavesPerGame,omitempty"`
	Blocks                       uint64  `json:"Blocks,omitempty"`
	Saves                        uint64  `json:"Saves,omitempty"`
	HighestSaves                 uint64  `json:"HighestSaves,omitempty"`
	GoalSavePercentage           float64 `json:"GoalSavePercentage,omitempty"`
	BlockPercentage              float64 `json:"BlockPercentage,omitempty"`
	GoalsPerGame                 float64 `json:"GoalsPerGame,omitempty"`
	Points                       uint64  `json:"Points,omitempty"`
	Goals                        uint64  `json:"Goals,omitempty"`
	Steals                       uint64  `json:"Steals,omitempty"`
	TwoPointGoals                uint64  `json:"TwoPointGoals,omitempty"`
	HighestPoints                uint64  `json:"HighestPoints,omitempty"`
	GoalScorePercentage          float64 `json:"GoalScorePercentage,omitempty"`
	AveragePointsPerGame         float64 `json:"AveragePointsPerGame,omitempty"`
	ThreePointGoals              uint64  `json:"ThreePointGoals,omitempty"`
	BounceGoals                  uint64  `json:"BounceGoals,omitempty"`
	ArenaMVPPercentage           float64 `json:"ArenaMVPPercentage,omitempty"`
	ArenaMVPS                    uint64  `json:"ArenaMVPs,omitempty"`
	CurrentArenaMVPStreak        uint64  `json:"CurrentArenaMVPStreak,omitempty"`
	HighestArenaMVPStreak        uint64  `json:"HighestArenaMVPStreak,omitempty"`
	HeadbuttGoals                uint64  `json:"HeadbuttGoals,omitempty"`
	HatTricks                    uint64  `json:"HatTricks,omitempty"`
}
